### ISSUE TITLE
Some emojis get replaced by NFKD

### ISSUE THREAD

**Issue by bobcogneato** [feederbox826/FansDB-SHALookup#4]
A few emojis get murdered by normalization: ❤️ and ☺️ are the only ones I've noticed so far

**Comment by feederbox826** [comment]
I think now that we have confusables we might be able to undo nfkd, I'll add it as a flag

**Comment by feederbox826** [comment]
beta in https://github.com/feederbox826/FansDB-SHALookup/commit/6e53bdf790cd93a06e98f01236356836a3ce4299

**Comment by feederbox826** [comment]
NFKD removed entirely in favor of confusabled
