### ISSUE TITLE
Longer titles get cut poorly

### ISSUE THREAD

**Issue by bobcogneato** [feederbox826/FansDB-SHALookup#5]
This won't be a trivial issue, and likely won't be able to be fixed completely without some kind of language model (which is certainly out of scope) but it may be possible to get at least better results by looking at punctuation.

What I'm thinking is take exactly what is there now, but scan starting at the end to find the first punctuation (except commas, probably) and cut just after it. But only if the resulting title is greater than some certain length.

**Comment by feederbox826** [comment]
I would love to figure out some sematic rule, but I agree - without some LLM it would be difficult - imo the comprimise we have now is just to hard cut at 64chars, it gives users some wiggle room to go longer or shorter based on thier own heuristics and context

**Comment by feederbox826** [comment]
resolved in https://github.com/feederbox826/FansDB-SHALookup/pull/10, v1.5.0 beta

**Comment by feederbox826** [comment]
merged, I'm still a bit unhappy with length truncation but unless we allow it to go beyond and/or implement an LLM, it's not terrible
